/**
 * Inbox - Generated Tickets Worklist
 * Displays all tickets generated by TP FAB Agents
 * Author: Vinod Kumar V (VKV)
 */

import { useState } from "react";
import { Store, Table2, List, Grid3x3 } from "lucide-react";
import TicketsTable from "./TicketsTable";

export default function Inbox({ onNavigate }) {
  const [viewMode, setViewMode] = useState("table"); // "table" | "list" | "grid"

  return (
    <div className="p-6">
      {/* Header with Back to Store button */}
      <div className="mb-6">
        <div className="flex items-center justify-between mb-4">
          <div className="flex-1">
            <h1 className="text-lg font-bold text-gray-900 dark:text-white mb-2">
              Inbox
            </h1>
            <p className="text-gray-600 dark:text-gray-400">
              All tickets generated by TP FAB Agents workflow orchestration. Click on a ticket to view details.
            </p>
          </div>
          
          <div className="flex items-center gap-3">
            {/* View Mode Toggle */}
            <div className="flex items-center gap-1 bg-gray-100 dark:bg-gray-800 rounded-lg p-1 border border-gray-200 dark:border-gray-700">
              <button
                onClick={() => setViewMode("table")}
                className={`p-2 rounded transition-all ${
                  viewMode === "table"
                    ? "bg-white dark:bg-gray-700 text-[#780096] shadow-sm"
                    : "text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-200"
                }`}
                title="Table View"
              >
                <Table2 className="w-4 h-4" />
              </button>
              <button
                onClick={() => setViewMode("list")}
                className={`p-2 rounded transition-all ${
                  viewMode === "list"
                    ? "bg-white dark:bg-gray-700 text-[#780096] shadow-sm"
                    : "text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-200"
                }`}
                title="List View"
              >
                <List className="w-4 h-4" />
              </button>
              <button
                onClick={() => setViewMode("grid")}
                className={`p-2 rounded transition-all ${
                  viewMode === "grid"
                    ? "bg-white dark:bg-gray-700 text-[#780096] shadow-sm"
                    : "text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-200"
                }`}
                title="Grid View"
              >
                <Grid3x3 className="w-4 h-4" />
              </button>
            </div>

            {/* Back to Store Button */}
            {onNavigate && (
              <button
                onClick={() => onNavigate("store")}
                className="flex items-center gap-1.5 px-2.5 py-1.5 text-xs font-medium text-gray-600 dark:text-gray-400 hover:text-[#780096] dark:hover:text-[#780096] rounded-lg hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
                title="Back to FAB Store"
              >
                <Store className="w-3.5 h-3.5" />
                <span className="hidden sm:inline">Store</span>
              </button>
            )}
          </div>
        </div>
      </div>

      {/* Tickets Display - Different views based on mode */}
      {viewMode === "table" ? (
        <TicketsTable
          onSelect={(ticket) => {
            console.log("Selected ticket:", ticket);
            // Future: Could navigate to ticket details or open in ticketing system
          }}
        />
      ) : viewMode === "list" ? (
        <div className="bg-white dark:bg-gray-900 rounded-lg border border-gray-200 dark:border-gray-800 shadow-sm">
          <TicketsTable
            onSelect={(ticket) => {
              console.log("Selected ticket:", ticket);
            }}
          />
        </div>
      ) : (
        <div className="bg-white dark:bg-gray-900 rounded-lg border border-gray-200 dark:border-gray-800 shadow-sm p-6">
          <div className="text-center py-12 text-gray-500 dark:text-gray-400">
            <Grid3x3 className="w-12 h-12 mx-auto mb-4 opacity-50" />
            <p className="text-sm">Grid view coming soon</p>
            <p className="text-xs mt-2">Switch to Table or List view to see tickets</p>
          </div>
        </div>
      )}
    </div>
  );
}
